version: '3.4'

services:
   db:
    build:
        context: ./
        target: database
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 679778
        POSTGRES_DB: covid
    ports:
        - "5432:5432"

   spring:
    build:
        context: ./
        target: jar
    environment:
        JDBC_URL: jdbc:postgresql://db:5432/covid
        DB_USERNAME: postgres
        DB_PASSWORD: 679778
    ports:
        - "8080:8080"